FROM almalinux:9 
ENV course="Devops with AWS" \ 
    trainer="Trinath Reddy" \ 
    duration="120HR"
ARG ${username:-some_user}
RUN echo "Hello ${username}" > /tmp/devops.txt 
CMD ["sleep", "100"]